### ISSUE TITLE
Undefined control sequence \xeCJKcaption{gb_452}

### ISSUE THREAD

**Issue by hijkzzz** [polossk/LaTeX-Template-For-NPU-Thesis#2]
\xeCJKcaption{gb_452}
这一行报错 Undefined control sequence
环境 macOS MacTex 2016 XeLaTex

**Comment by polossk** [comment]
两个解决方案
A 自行下载xeCJK宏包
B 使用 XeTeX编译

**Comment by polossk** [comment]
现在有两个解决方案:
第一种, 把文件 `gb_452.cpx` 添加到当前的工作目录;
第二种, 删除这句话, 同时修改 `thesis-setting.tex` 文件中的目录相关的代码, 使其格式与论文要求一致.

**Comment by Pokerpoke** [comment]
![issue](https://cloud.githubusercontent.com/assets/16596257/26032240/47f4011c-38c1-11e7-9221-b2de43b61459.png)
Windows 下gb_452.cpx添加到当前工作目录还会有问题，Ubuntu下没有这个问题，第二种方法找到的一个解决方法是，但是不知道会不会影响什么。
```
\usepackage{CJKnumb}
% \xeCJKcaption{gb_452}
```

**Comment by hijkzzz** [comment]
\xeCJKcaption 这个函数在新版中删除了 所以别用2016

**Comment by polossk** [comment]
我注意到了你们二者所提到的问题，我会尽快尝试完全与这个cpx文件进行切割。

如果你们已有较好的解决方案，不妨新开分支并且发pull request，我会及时处理。
