### ISSUE TITLE
帮忙发字体——已star

### ISSUE THREAD

**Issue by HongYegg** [polossk/LaTeX-Template-For-NPU-Thesis#22]
您好！那个字体链接我进不去，翻墙挂掉了，下载不了。能不能请您发我一份。万分感谢。

**Comment by HongYegg** [comment]
已解决

**Comment by HongYegg** [comment]
<img width="734" alt="批注 2020-04-26 114017" src="https://user-images.githubusercontent.com/62496073/80297110-fd310c80-87b2-11ea-994e-24e9c1b27d72.png">   请问为啥加了字体  还是报错

**Comment by polossk** [comment]
整个 repo 用到的 Adobe 字体有如下四种：

* 宋体，字体名 `Adobe Song Std`
* 黑体，字体名 `Adobe Heiti Std`
* 楷体，字体名 `Adobe Kaiti Std`
* 仿宋体，字体名 `Adobe Fangsong Std`

请首先确认自己已经安装这四种字体，您的报错输出明显是未安装字体

**Comment by HongYegg** [comment]
![image](https://user-images.githubusercontent.com/62496073/80297660-ba256800-87b7-11ea-926c-bd0b8290317c.png)
谢谢，我安装好了吧

**Comment by HongYegg** [comment]
我也刷新过好多次了

**Comment by polossk** [comment]
关掉所有的控制台，重新打开一个管理员模式下运行的控制台，输入 `fc-cache -f -v` 重新刷新字体缓存，等待输出完成之后，再尝试编译

**Comment by HongYegg** [comment]
还是找不到   会不会是你编写的文件里名称不对   加后缀啥的  我在试试   谢谢你

**Comment by polossk** [comment]
字体这个是因为当你有 Adobe Acrobat 之后，Acrobat 会将 Adobe 的字体安装至你的电脑，而且他的字体表现是由于普通 Windows 内置字体的，所以才会在设置里添加字体设置。但是基于授权协议，这个项目无法直接公开上传 Adobe 公司的字体。所以解决方案有两个。

1. 安装正版 Adobe Acrobat 获得正确的字体
2. 自行修改字体名保证 tex 能够正确索引

本人不在回答任何关于 tex 使用而非本 repo 的任何问题

**Comment by polossk** [comment]
另外，这个 issue 我的所有解决方案均在 readme 中已经提及，所以请在 readme 的建议下自行处理自己遇到的问题
