### ISSUE TITLE
目录中不显示中英文摘要还有目录

### ISSUE THREAD

**Issue by GroverZhu** [polossk/LaTeX-Template-For-NPU-Thesis#30]
作者你好，请问怎么设置才能在目录中不显示中文摘要/英文摘要还有目录这三个内容？
![image](https://user-images.githubusercontent.com/29880160/83947160-faace280-a847-11ea-8394-5fbb5a8b2d43.png)

**Comment by polossk** [comment]
您好！这三个内容是通过 `section` 或者手动添加 `addcontent` 实现的，请自行删除相关代码或者使用 `section*` 即可
