### ISSUE TITLE
可以尝试兼容overleaf？

### ISSUE THREAD

**Issue by EzioZz** [polossk/LaTeX-Template-For-NPU-Thesis#31]
overleaf是一个很好用的latex在线编辑环境，具有批注、在线聊天等功能。
目前在overleaf平台因为缺失adobe字体，会产生报错。

**Comment by polossk** [comment]
您好，使用adobe字体的初衷是由于默认字体的排版效果不佳。如果您执意在overleaf上使用，可以参考本链接 https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis/issues/23 进行相应的字体设置。

**Comment by EzioZz** [comment]
好的谢谢
