### ISSUE TITLE
引入amsmath包后所有的公式引用都变成了(??)

### ISSUE THREAD

**Issue by npuzl** [polossk/LaTeX-Template-For-NPU-Thesis#33]
因为需要使用公式对齐，引入了amsmath包，然后使用\ref引用公式，会导致引用的公式都是(??)

**Comment by polossk** [comment]
请您多次编译一下latex，有可能是aux辅助文件的数据没有正确更新。
如果问题没有解决，麻烦您提供一份最小的可复现环境，我帮您测试下。

**Comment by npuzl** [comment]
收到！

**Comment by npuzl** [comment]
感谢回复，已经解决了，如果不在设置文件里面加入usepackage{amsmath}，texstudio会提示\begin{aligned}环境有问题，但实际上是可以编译出来的，加了usepackage{amsmath}后texstudio的提示消失了，但是编译后公式引用变成了(??)，所以最后的解决方案就是不管texstudio的提示




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shangkun ***@***.***&gt;; 
发送时间: 2022年5月27日(星期五) 凌晨0:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [polossk/LaTeX-Template-For-NPU-Thesis] 引入amsmath包后所有的公式引用都变成了(??) (Issue #33)





 
请您多次编译一下latex，有可能是aux辅助文件的数据没有正确更新。
 如果问题没有解决，麻烦您提供一份最小的可复现环境，我帮您测试下。

**Comment by polossk** [comment]
ok，感谢反馈，我们会把你的这个经验添加至 readme 文件中以帮助更多的同学。
