### ISSUE TITLE
正文部分格式

### ISSUE THREAD

**Issue by WuTao-CS** [polossk/LaTeX-Template-For-NPU-Thesis#34]
您好，首先非常感谢各位的贡献的Latex模板，非常好用！
根据学校教务处发布的word模板，正文部分标题前应该是两行小四空格
![正文格式](https://user-images.githubusercontent.com/48761159/170868792-10deab29-abb8-41ed-aad7-3508a61bf6cf.png)
但是实际使用模板好像编译结果为
![实际](https://user-images.githubusercontent.com/48761159/170868879-5ed84d55-039f-4336-99c6-35af5cdcd961.png)
想请教一下这个是bug还是什么其他原因？

**Comment by polossk** [comment]
感谢比对，最近工作比较忙，这两天我会处理下

**Comment by polossk** [comment]
已确认是bug，等待后续更新

**Comment by polossk** [comment]
请按照最新模板使用，如有其它问题也欢迎提出来。
