### ISSUE TITLE
摘要，目录等部分的页码应当是大写罗马字符

### ISSUE THREAD

**Issue by npuzl** [polossk/LaTeX-Template-For-NPU-Thesis#37]
摘要，目录等部分的页码应当是大写罗马字符，但实际编译出来是小写罗马字符，与现在模板要求不符
![image](https://user-images.githubusercontent.com/53386473/172053880-e2be7652-fd35-43b2-800a-8550cea09069.png)

**Comment by polossk** [comment]
收到，请等待更新
