### ISSUE TITLE
关于数字和字母的times new Roman字体未正确设置，另外Latex行间距与word行间距不能简单换算

### ISSUE THREAD

**Issue by AowerDmax** [polossk/LaTeX-Template-For-NPU-Thesis#39]
打印论文后发现，论文行间距明显比word模板要小很多，看起来有点像1倍行间距的问题，然后就是字母（英文）和数字没用采用times new Roman 字体，差别很明显。

相关链接[知乎](https://www.zhihu.com/question/62327906#:~:text=baselinestretch%20%E6%98%AF%E4%B8%AA%E5%B1%95%E5%BC%80%E4%B8%BA%E4%B8%80%E4%B8%AA%E6%95%B0%E5%80%BC%E6%AF%94%E4%BE%8B%E7%9A%84%E5%AE%8F%EF%BC%8C%E5%AE%83%E7%94%B1%20linespread%20%E6%8E%A7%E5%88%B6%E3%80%82%20fontsize%20%E7%9A%84%E7%AC%AC%E4%B8%80%E4%B8%AA%E5%8F%82%E6%95%B0%E6%98%AF%E5%AD%97%E5%8F%B7%EF%BC%8C%E7%AC%AC%E4%BA%8C%E4%B8%AA%E5%8F%82%E6%95%B0%E6%98%AF%E5%9F%BA%E6%9C%AC%E8%A1%8C%E8%B7%9D%EF%BC%8C%E5%9C%A8%20LaTeX%20%E5%86%85%E9%83%A8%E5%9F%BA%E6%9C%AC%E8%A1%8C%E8%B7%9D%E7%94%A8%E5%8F%98%E9%87%8F,%E4%BF%9D%E5%AD%98%E3%80%82%20%E5%9C%A8%E5%AD%97%E5%8F%B7%E7%94%9F%E6%95%88%E6%97%B6%EF%BC%8CLaTeX%20%E4%BC%9A%E8%AE%BE%E7%BD%AE%E8%A1%8C%E8%B7%9D%20baselineskip%20%3D%20linespread%20%E4%B9%98%E4%BB%A5%20normalbaselineskip%E3%80%82)

**Comment by AowerDmax** [comment]
另外附上[最新的一版毕业论文模板pdf实例](https://wwm.lanzouq.com/iOp0I069es0d)，后续解决方法会在Issues里面添加

**Comment by polossk** [comment]
感谢提醒，我们后续也会进行更改，英文字母这个可以参考 另一个硕博论文模板的处理方式，行距改下 \baselineskip 吧

**Comment by AowerDmax** [comment]
非常感谢作者的回答，关于英文和字母问题，可以在进行设置
```latex
%---------------------------------设置中文字体---------------------------------%
\usepackage{fontspec}
\usepackage[SlantFont,BoldFont,CJKchecksingle]{xeCJK}
\usepackage{CJKnumb}
% 使用 Adobe 字体
\newcommand\defaultSog{SimSun}                      % 宋体, 用于正文
\newcommand\defaultHei{SimHei}                      % 黑体, 用于标题
\newcommand\defaultKai{KaiTi}                       % 楷体, 一般用于强调
\newcommand\defaultFag{FangSong}                    % 仿宋, 一般用于强调
\newcommand\codeFont{Consolas}
%%-----------------------------------------------------------------------------%
\newcommand\defaultEngFont{Times New Roman}                 % 英文文本默认字体                    
% 设置字体
\defaultfontfeatures{Mapping=tex-text}                      % 启用 TeX Ligatures
\setCJKmainfont[ItalicFont=\defaultKai, BoldFont=\defaultHei]{\defaultSog}
\setCJKsansfont[ItalicFont=\defaultKai, BoldFont=\defaultHei]{\defaultSog}
\setCJKfamilyfont{song}{\defaultSog}                        % 设置 CJK 字体族
\setCJKfamilyfont{hei}{\defaultHei}                         %
\setCJKfamilyfont{kai}{\defaultKai}                         %
\setCJKfamilyfont{fang}{\defaultFag}                        %
\setCJKfamilyfont{eng}{\defaultEngFont}                     %
\setmonofont{\codeFont}                                     %
\setmainfont{\defaultEngFont}                               %
\setCJKfamilyfont{nwpu}{nwpuname}
\newcommand{\fSong}{\CJKfamily{song}}                       % 宋体: fSong
\newcommand{\fHei}{\CJKfamily{hei}}                         % 黑体: fHei
\newcommand{\fKai}{\CJKfamily{kai}}                         % 楷体: fKai
\newcommand{\fFang}{\CJKfamily{fang}}                       % 仿宋: fFang
\newcommand{\fEng}{\CJKfamily{eng}}                         % 英文: fEng
\newcommand{\fNWPU}{\CJKfamily{nwpu}}
%------------------------------------------------------------------------------%
```

至于行间距问题，可以通过在每个子tex文件中开头添加以下代码
```latex
\renewcommand{\baselinestretch}{1.5}
\fontsize{12pt}{13pt}\selectfont
```
但是因为word的行间距并不是固定的，依靠字体的大小，上面的设置只能在times new roman宋体小四号上和word有相同的效果

如何根据标题的字体大小来动态的设置行间距？请多指教

**Comment by polossk** [comment]
我当初的方法比较笨拙，你可以看到我当初在 setting 里字体字号设置了很多，甚至同字号不同行距的也有多种（比如万恶小四）。考虑到论文相对而言格式比较稳定，字号也相对统一，所以我个人建议不如你直接把默认的小四字号那里选择一下，或者直接使用目前现有的，比如当前的这个` \sLargeHalfXiaosi` 似乎基本吻合。
```tex
\newcommand{\sHalfXiaosi}{\fontsize{12.5pt}{16.25pt}\selectfont}        % 半小四, 1.25倍
\newcommand{\sLargeHalfXiaosi}{\fontsize{13pt}{19pt}\selectfont}        % 半小四, 1.5倍
\newcommand{\sXiaosi}{\fontsize{12pt}{14.4pt}\selectfont}               % 小四, 1.25倍
```

**Comment by npuzl** [comment]
> 

您好，我按照这个设置，数学环境内的字体仍然不是times new roman，请问有办法让数学环境内字体变成times new roman吗

**Comment by polossk** [comment]
@npuzl 首先我不理解为什么需要把数学环境内的字体变成times new roman，我不记得有任何要求需要这么做，印象里我只记得有正文部分的英文使用times new roman字体这一规定要求。
如果你实在是需要这么搞，参考这份回答吧 [LaTeX数学公式的默认字体是什么？ - Chazeon的回答 - 知乎](https://www.zhihu.com/question/30058577/answer/46632535)

**Comment by npuzl** [comment]
> @npuzl 首先我不理解为什么需要把数学环境内的字体变成times new roman，我不记得有任何要求需要这么做，印象里我只记得有正文部分的英文使用times new roman字体这一规定要求。 如果你实在是需要这么搞，参考这份回答吧 [LaTeX数学公式的默认字体是什么？ - Chazeon的回答 - 知乎](https://www.zhihu.com/question/30058577/answer/46632535)

在答辩时老师指出了我这个问题，因为别人用的word，公式字体是TimesNewRoman，比latex模板里面的公式字体粗一点，且小写字母i的差异很明显，这个问题被老师指出了，要求我改正

**Comment by AowerDmax** [comment]
> @npuzl 

针对数学环境中的字体问题，个人的解决方法为，在`thesis-setting.tex`中添加以下代码
```latex
\usepackage[T1]{fontenc}
\usepackage{newtxmath}
```
mathptmx 是一个为 LaTeX 设计的字体宏包，它会将默认 rmfamily 设置为 Nimbus Roman No9 L；而将数学字体设置为对应的 Italic 字形（不足的部分使用了 CM/RSFS/Adobe Symbol 等字体）。这是同时修改默认文本字形和默认数学字形为 Times 字形最干净的宏包。 使用它可能需要借助 fontenc 宏包来辅助设置字体编码。

[参考链接](https://www.latexstudio.net/archives/9323.html)

**注意，可能需要手动调整数学模式下的符号间距**

**Comment by AowerDmax** [comment]
如果有更好的解决方案，请多指教，[参考链接](https://www.latexstudio.net/archives/9323.html)中的第一种解决方案，我在我这里并没用生效，在我的观察下，上面的方案应该是达到了`times new roman`字体的效果， 我主要观察的是字母 `G` 的形状

发现大写字母`Q`的样式还是不对，在公式里面,目前的解决方案是
```latex
%添加文本环境
$ \text{Q} $
```

**Comment by polossk** [comment]
我说下我个人的理解哈。一般来说，文章中的数学符号的字体都是建议使用数学环境的，而且不同类型的符号也应该使用不同的字体形式，比如三角函数`y=sin(x)`这种就应该使用 `$y=\sin(x)$` 来显示为 $y=\sin(x)$ 而不是使用 `$y=sin(x)$` 来显示为 $y=sin(x)$。所以泛泛来讲，全文只要保持数学符号的**统一、清晰、规范**，我个人理解这个工作已经足够了。

我能够理解有答辩评委老师指出关于字体的问题，但是你也要批判的去看这个问题究竟是好问题还是垃圾问题。如果你的论文本身已经做到了数学符号的**统一、清晰、规范**，只是某些地方的字体与 word 的输出不同，我并不觉得这个问题是一个好问题。

而且，Times New Roman 本身就是一种历史遗留问题，而且仅这种字体有多种变体。所以我的建议是，不要在这种细枝末节上浪费过多的时间。

参考文档：
1. <https://liam.page/2017/01/10/Times-New-Roman-and-LaTeX/>
2. <https://zhuanlan.zhihu.com/p/506189673>

**Comment by gilgamsh** [comment]
> ```
> , 1.5倍
> ```

关于行间距1.25的问题，看了issue我还是有一些疑惑。请问您是按照这个quote回答里面这样解决的吗？

**Comment by npuzl** [comment]
收到！
