### ISSUE TITLE
数学公式应当是Times New Roman字体

### ISSUE THREAD

**Issue by npuzl** [polossk/LaTeX-Template-For-NPU-Thesis#40]
在发的模板中，公式是TimesNewRoman字体，对比于本模板用的字体，Times New Roman字体更粗，建议模板改一下，可能有些老师在答辩的时候会提这个问题

**Comment by polossk** [comment]
您好！
当时的版本未指定英文字体，请参考 #39 的内容进行设置。
数学公式字体是选择了 $\LaTeX$ 默认的设置，参考 [LaTeX数学公式的默认字体是什么？ - 孟晨的回答 - 知乎](https://www.zhihu.com/question/30058577/answer/46612848)。
