### ISSUE TITLE
关于参考文献的格式（是否空行）

### ISSUE THREAD

**Issue by merengueLee** [polossk/LaTeX-Template-For-NPU-Thesis#41]
这个学校模版没有明确说明（如图），模版是直接空一行，存在有老师认为格式不对的问题，请问这个怎么修改呢？
<img width="614" alt="截屏2022-06-16 23 22 25" src="https://user-images.githubusercontent.com/50510116/174104485-72964a94-9787-4775-a0a6-0e8f81d1ae3b.png">

**Comment by polossk** [comment]
您好！
是这样的，默认环境绝大多数老师和学生还是认可的，所以这个不在修复范围之内。
TeX问题的话，优先搜索引擎吧，这样比较快，我不一定有空回复您。
在引用参考文献的章节前，添加如下代码
```tex
\newlength\olditemsep
\setlength{\olditemsep}{itemsep}
\setlength{\itemsep}{15pt} % 或者你认为合适的宽度
```
参考文献部分结束后，将间隔还原即可
```tex
\setlength{\itemsep}{\olditemsep}
```

**Comment by merengueLee** [comment]
> 您好！ 是这样的，默认环境绝大多数老师和学生还是认可的，所以这个不在修复范围之内。 TeX问题的话，优先搜索引擎吧，这样比较快，我不一定有空回复您。 在引用参考文献的章节前，添加如下代码
> 
> ```
> \newlength\olditemsep
> \setlength{\olditemsep}{itemsep}
> \setlength{\itemsep}{15pt} % 或者你认为合适的宽度
> ```
> 
> 参考文献部分结束后，将间隔还原即可
> 
> ```
> \setlength{\itemsep}{\olditemsep}
> ```
明白了，感谢前辈的回复
