### ISSUE TITLE
如何在附录中分节

### ISSUE THREAD

**Issue by CarlDegio** [polossk/LaTeX-Template-For-NPU-Thesis#44]
在附录中直接使用section，会因为停止分章编号而得到上一章的大编号。
而如果引入appendix，又回没有附录的章节编号，如图
![image](https://user-images.githubusercontent.com/52379582/177920216-d928c434-efb0-478e-933d-265073c7f736.png)
正确的附录分节方式应该怎么办？

**Comment by polossk** [comment]
这个是因为`\backmatter`内自动取消了所有的 chapter 编号导致的。
请参考 https://github.com/NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis 的附录实现
